# Generated by Django 3.1.5 on 2021-01-30 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='email',
            new_name='id_contact_email',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='msg',
            new_name='id_contact_msg',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='subject',
            new_name='id_contact_subject',
        ),
    ]
