# Generated by Django 3.1.5 on 2021-01-30 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_auto_20210130_1648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='form',
            old_name='id_contact_email',
            new_name='contact_email',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='id_contact_msg',
            new_name='contact_message',
        ),
        migrations.RenameField(
            model_name='form',
            old_name='id_contact_subject',
            new_name='contact_subject',
        ),
    ]
